version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  groups:
    ci:
      dependency-type: "development"
      patterns:
        - "mypy*"
        - "pytest*"
        - "ruff*"
        - "pre-commit"
        - "codecov"
        - "towncrier"
    doc:
      dependency-type: "development"
      patterns:
        - "sphinx*"
        - "alabaster"
